CREATE TABLE IF NOT EXISTS PUBLIC.FILMS (
	FILM_ID INTEGER NOT NULL PRIMARY KEY,
	TITLE varchar(200) NOT NULL,
	DESCRIPTION varchar(200),
	RELEASE_DATE DATE NOT NULL,
	DURATION INTEGER NOT NULL,
	RATING_ID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.GENRES (
	GENRE_ID INTEGER NOT NULL PRIMARY KEY,
	GENRE_TITLE varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILM_GENRE (
	FILM_ID INTEGER NOT NULL REFERENCES PUBLIC.FILMS(FILM_ID),
	GENRE_ID INTEGER NOT NULL REFERENCES PUBLIC.GENRES(GENRE_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
	USER_ID INTEGER NOT NULL PRIMARY KEY,
	EMAIL varchar(200) NOT NULL,
	LOGIN varchar(50) NOT NULL,
	NAME varchar(200) NOT NULL,
	BIRTHDAY DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDS (
	USER_ID INTEGER NOT NULL REFERENCES PUBLIC.USERS(USER_ID),
	FRIEND_ID INTEGER NOT NULL REFERENCES PUBLIC.USERS(USER_ID),
	IF_APPROVED BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.RATINGS (
	RATING_ID INTEGER NOT NULL PRIMARY KEY,
	RATING_NAME varchar(20) NOT NULL REFERENCES PUBLIC.FILMS(FILM_ID)
);


CREATE TABLE IF NOT EXISTS PUBLIC.LIKES (
	FILM_ID INTEGER NOT NULL REFERENCES PUBLIC.FILMS(FILM_ID),
	USER_ID INTEGER NOT NULL REFERENCES PUBLIC.USERS(USER_ID)
);